# Nav2 params for localization mode with RTAB-Map
# Uses global frame = map, static layer from RTAB-Map /map, plus obstacles

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    default_nav_to_pose_bt_xml: /opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    default_nav_through_poses_bt_xml: /opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
    navigators: ['navigate_to_pose', 'navigate_through_poses']
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 15.0
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 60.0
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.15
      lookahead_dist: 2.5
      min_lookahead_dist: 1.8
      max_lookahead_dist: 3.0
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.20
      transform_tolerance: 0.1
      min_approach_linear_velocity: 0.10
      approach_velocity_scaling_dist: 0.5
      use_collision_detection: true
      allow_reversing: false
      max_angular_accel: 0.15

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    use_sim_time: false
    simulate_ahead_time: 2.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 15.0
      publish_frequency: 15.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 20
      height: 20
      resolution: 0.05
      robot_radius: 0.093
      transform_tolerance: 10.0
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 0.8
        min_obstacle_height: 0.10
        unknown_threshold: 10
        mark_threshold: 2
        tf_filter_tolerance: 5.0
        observation_sources: pointcloud
        pointcloud:
          data_type: PointCloud2
          topic: /camera/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 2.5
          raytrace_max_range: 3.5
          raytrace_min_range: 0.25
          min_obstacle_height: 0.10
          max_obstacle_height: 0.8
          expected_update_rate: 0.0
          observation_persistence: 0.0
          clearing_use_maximum_range: true
          inf_is_valid: false
          filter_ground: true
          ground_filter_min_height: 0.0
          ground_filter_max_height: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.8

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.093
      resolution: 0.05
      track_unknown_space: true
      rolling_window: false
      width: 200
      height: 200
      transform_tolerance: 5.0
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/map"                 # RTAB-Map occupancy
        subscribe_to_updates: true
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: pointcloud
        footprint_clearing_enabled: true
        max_obstacle_height: 0.8
        min_obstacle_height: 0.10
        combination_method: 1
        pointcloud:
          data_type: PointCloud2
          topic: /camera/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 2.5
          raytrace_max_range: 3.5
          raytrace_min_range: 0.25
          min_obstacle_height: 0.10
          max_obstacle_height: 0.8
          expected_update_rate: 0.0
          observation_persistence: 0.0
          clearing_use_maximum_range: true
          inf_is_valid: false
          filter_ground: true
          ground_filter_min_height: 0.0
          ground_filter_max_height: 0.1
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 15.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.25, 0.0, 0.5]
    min_velocity: [-0.25, 0.0, -0.5]
    max_accel: [1.0, 0.0, 0.8]
    max_decel: [-1.0, 0.0, -0.8]
    odom_topic: "/odometry/filtered"
    reset_on_start: true
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel_safe"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.5
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    observation_sources: ["pointcloud"]
    pointcloud:
      type: "pointcloud"
      topic: "/camera/depth/color/points"
      min_height: 0.10
      max_height: 2.0
      enabled: True
    polygons: ["safety_polygon", "slow_polygon"]
    safety_polygon:
      type: "circle"
      radius: 0.08
      action_type: "stop"
      min_points: 6
      visualize: True
      polygon_pub_topic: "safety_polygon"
    slow_polygon:
      type: "circle"
      radius: 0.20
      action_type: "slowdown"
      slowdown_ratio: 0.5
      min_points: 4
      visualize: True
      polygon_pub_topic: "slow_polygon"

