amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"  # Consistent with SLAM
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 8.0 # Max effective range of the /realsense_435i/scan (tune based on depthimage_to_laserscan settings)
    laser_min_range: 0.15 # Min effective range of the /realsense_435i/scan
    laser_model_type: "likelihood_field"
    max_beams: 180 # Increased from 60, tune based on actual scan from depthimage_to_laserscan quality.
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: /scan # Corrected topic

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: odom
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    # plugin_lib_names should be empty for standard Nav2 - all plugins auto-loaded in Jazzy+
    # Use Nav2 default behavior trees with absolute paths
    default_nav_to_pose_bt_xml: /opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    default_nav_through_poses_bt_xml: /opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
    navigators: ['navigate_to_pose', 'navigate_through_poses']
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 15.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] 
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 60.0  # Give much more time to find path
    
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
    
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.15  # Much slower for better control
      lookahead_dist: 2.5  # Increased lookahead for smoother path planning
      min_lookahead_dist: 1.8
      max_lookahead_dist: 3.0
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.20  # Increased for better turning response
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.10  # Much slower minimum speed for better control
      approach_velocity_scaling_dist: 0.5  # Scale velocity sooner
      use_collision_detection: false  # Disable for outdoor mapping
      max_allowed_time_to_collision_up_to_carrot: 5.0
      use_regulated_linear_velocity_scaling: false  # Disable conservative scaling
      use_cost_regulated_linear_velocity_scaling: false  # Disable cost-based scaling
      cost_scaling_dist: 0.6
      cost_scaling_gain: 1.0
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.10  # Much slower for better control
      use_rotate_to_heading: false  # Disable to reduce excessive turning
      allow_reversing: false
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 0.15  # Increased angular acceleration for better turning
      max_robot_pose_search_dist: 10.0
      use_interpolation: false

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 15.0  # Match camera frame rate for better sync
      publish_frequency: 15.0  # Match camera frame rate for better sync
      global_frame: odom  # Use odom frame for SLAM - critical for proper anchoring
      robot_base_frame: base_footprint  # Consistent with SLAM
      use_sim_time: False
      rolling_window: true
      width: 8  # Larger for better forward planning
      height: 8  # Larger for better forward planning
      resolution: 0.05  # Higher resolution for better obstacle detection
      robot_radius: 0.15
      transform_tolerance: 5.0  # Increased for severe timing issues
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 0.8
        min_obstacle_height: 0.50  # Filter out ground plane - only detect obstacles above 50cm
        unknown_threshold: 10
        mark_threshold: 2
        tf_filter_tolerance: 2.0  # Increased for transform timing
        observation_sources: pointcloud
        pointcloud:
          data_type: PointCloud2
          topic: /camera/camera/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 3.0
          raytrace_max_range: 4.0
          raytrace_min_range: 0.15
          min_obstacle_height: 0.50  # Filter out floor - ignore anything below 50cm height
          max_obstacle_height: 0.8   # Increased for better obstacle detection
          expected_update_rate: 0.0
          observation_persistence: 0.0
          clearing_use_maximum_range: true
          inf_is_valid: false
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0  # Increased penalty near obstacles
        inflation_radius: 0.8  # Larger safety buffer
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0  # Adequate for global planning
      publish_frequency: 1.0  # Adequate for global planning
      global_frame: odom  # Use odom frame for odometry-based navigation (no SLAM)
      robot_base_frame: base_footprint  # Consistent with SLAM
      use_sim_time: False
      robot_radius: 0.15
      resolution: 0.05  # Higher resolution for better path planning
      track_unknown_space: true
      rolling_window: true  # Use rolling window during SLAM
      width: 50  # Rolling window size
      height: 50  # Rolling window size
      transform_tolerance: 2.0  # Increased for severe timing issues
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: pointcloud
        footprint_clearing_enabled: true
        max_obstacle_height: 0.8
        min_obstacle_height: 0.50  # Filter out ground plane detection
        combination_method: 1
        pointcloud:
          data_type: PointCloud2
          topic: /camera/camera/depth/color/points
          marking: true
          clearing: true
          obstacle_range: 2.5
          raytrace_max_range: 3.5
          raytrace_min_range: 0.15
          min_obstacle_height: 0.50  # Filter out floor - ignore anything below 50cm height
          max_obstacle_height: 0.8   # Increased for better obstacle detection
          expected_update_rate: 0.0
          observation_persistence: 0.0
          clearing_use_maximum_range: true
          inf_is_valid: false
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "yard_map.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    global_frame: odom
    robot_base_frame: base_footprint  # Consistent with SLAM
    transform_tolerance: 0.1
    use_sim_time: false
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 15.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.25, 0.0, 0.5]  # Increased angular velocity for better turning
    min_velocity: [-0.25, 0.0, -0.5]  # Increased angular velocity for better turning
    max_accel: [1.0, 0.0, 0.8]  # Increased angular acceleration for better turning
    max_decel: [-1.0, 0.0, -0.8]  # Increased angular deceleration for better turning
    odom_topic: "/odom"
    reset_on_start: true
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_footprint"  # Consistent with SLAM
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.5
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    observation_sources: ["pointcloud"]
    pointcloud:
      type: "pointcloud"
      topic: "/camera/camera/depth/color/points" # Corrected topic
      min_height: 0.02  # Camera 12.3cm high - filter ground plane
      max_height: 1.5  # Reduced from 2.0 to ignore higher objects
      enabled: True
    polygons: ["safety_polygon", "slow_polygon"]
    safety_polygon:
      type: "circle"
      radius: 0.3  # Immediate stop zone
      action_type: "stop"
      min_points: 4
      visualize: True
      polygon_pub_topic: "safety_polygon"
    slow_polygon:
      type: "circle"
      radius: 0.8  # Slow down zone
      action_type: "slowdown"
      slowdown_ratio: 0.3
      min_points: 4
      visualize: True
      polygon_pub_topic: "slow_polygon"
