pointcloud_to_laserscan:
  target_frame: "base_footprint"
  transform_tolerance: 0.1
  min_height: 0.15
  max_height: 0.25
  angle_min: -1.57
  angle_max: 1.57
  angle_increment: 0.017
  scan_time: 0.1
  range_min: 0.3
  range_max: 5.0
  use_inf: true
