realsense2_camera:
  ros__parameters:
    # Device configuration
    camera_name: "camera"
    camera_namespace: "camera"
    
    # Stream profiles - optimized for 32GB RAM system (higher quality/throughput)
    depth_module:
      depth_profile: 848x480x30  # Higher res + frame rate with abundant RAM
      enable_auto_exposure: true
      emitter_enabled: 1  # Enable IR emitter for better depth quality
      laser_power: 150.0  # Moderate laser power
    
    rgb_camera:
      color_profile: 848x480x30  # Match depth resolution and higher FPS
    
    # Enable required streams for pointcloud
    enable_color: true   # Required for pointcloud texturing
    enable_depth: true
    enable_sync: true    # Sync color and depth frames
    
    # Pointcloud configuration
    pointcloud:
      enable: true
      stream_filter: 2     # Use depth stream as base
      allow_no_texture_points: true
      ordered_pc: false
    
    # Depth alignment - critical for proper pointcloud
    align_depth:
      enable: true
    
    # Enable IMU with abundant processing power
    enable_infra1: false  # Keep these off to save USB bandwidth
    enable_infra2: false
    enable_gyro: true     # Enable for better pose estimation
    enable_accel: true    # Enable for motion detection
    
    # Enhanced filters for high-quality point clouds (32GB RAM allows more processing)
    decimation_filter:
      enable: false  # Disable to maintain full resolution with abundant RAM
    
    temporal_filter:
      enable: true   # Enable for noise reduction
      smooth_alpha: 0.4
      smooth_delta: 20
      persistence_control: 3
    
    spatial_filter:
      enable: true   # Enable for edge preservation
      smooth_alpha: 0.5
      smooth_delta: 20
      magnitude: 2
      holes_fill: 0
    
    hole_filling_filter:
      enable: true   # Fill holes in depth data
      holes_fill: 1
    
    # TF and performance settings
    publish_tf: true
    tf_publish_rate: 10.0
    
    # USB stability
    initial_reset: true
    reconnect_timeout: 5.0
    wait_for_device_timeout: 5.0