# Low bandwidth RealSense configuration for USB stability
camera_name: "camera"
camera_namespace: "camera"

# Core features - minimal bandwidth
enable_sync: true
enable_pointcloud: true
pointcloud.enable: true
align_depth.enable: true

# Low resolution settings to reduce USB bandwidth
depth_module.enable: true
depth_module.depth_profile: "320x240x6"  # Minimal resolution/framerate
rgb_camera.enable: true
rgb_camera.color_profile: "320x240x6"    # Match depth resolution

# Disable bandwidth-heavy features
enable_gyro: false
enable_accel: false
enable_infra1: false
enable_infra2: false

# Filters to reduce point cloud density
decimation_filter.enable: true
decimation_filter.magnitude: 4
temporal_filter.enable: false  # Disable to reduce processing
spatial_filter.enable: false   # Disable to reduce processing
hole_filling_filter.enable: false  # Disable to reduce processing

# Power/bandwidth optimizations
depth_module.emitter_enabled: 0  # Disable IR emitter (0=off, 1=on, 2=auto)
clip_distance: 3.0