realsense2_camera:
  ros__parameters:
    # Device configuration
    camera_name: "camera"
    camera_namespace: "camera"
    
    # Stream profiles - balanced for performance and quality
    depth_module:
      depth_profile: 640x480x15
      enable_auto_exposure: true
      emitter_enabled: 0  # Disable IR emitter for power saving
      laser_power: 0.0
    
    rgb_camera:
      color_profile: 640x480x15  # Match depth resolution
    
    # Enable required streams for pointcloud
    enable_color: true   # Required for pointcloud texturing
    enable_depth: true
    enable_sync: true    # Sync color and depth frames
    
    # Pointcloud configuration
    pointcloud:
      enable: true
      stream_filter: 2     # Use depth stream as base
      allow_no_texture_points: true
      ordered_pc: false
    
    # Depth alignment - critical for proper pointcloud
    align_depth:
      enable: true
    
    # Disable unnecessary streams to reduce USB bandwidth
    enable_infra1: false
    enable_infra2: false
    enable_gyro: false
    enable_accel: false
    
    # Filters for performance
    decimation_filter:
      enable: true
      magnitude: 2  # Reduce from 4 for better quality
    
    temporal_filter:
      enable: false
    
    spatial_filter:
      enable: false
    
    hole_filling_filter:
      enable: false
    
    # TF and performance settings
    publish_tf: true
    tf_publish_rate: 10.0
    
    # USB stability
    initial_reset: true
    reconnect_timeout: 5.0
    wait_for_device_timeout: 5.0