pointcloud_to_laserscan:
  ros__parameters:
    target_frame: "base_footprint"  # Use base_footprint for consistency with nav2
    transform_tolerance: 1.0  # Increased tolerance for timing issues
    min_height: 0.10  # Slightly lower to detect closer obstacles
    max_height: 0.30  # Slightly higher to capture more of the robot
    angle_min: -1.57
    angle_max: 1.57
    angle_increment: 0.017
    scan_time: 0.1
    range_min: 0.25  # Reduced to detect closer obstacles
    range_max: 4.0   # Reduced for better near-field accuracy
    use_inf: true
