# RealSense configuration - COLOR CAMERA ONLY
# Disable depth stream to avoid USB bandwidth issues

camera_name: "camera"
camera_namespace: "camera"

# Core features - minimal bandwidth
enable_sync: false  # Disable sync since no depth
enable_pointcloud: false  # Disable point cloud
align_depth.enable: false  # No depth alignment needed

# DISABLE depth module completely
depth_module.enable: false
enable_infra1: false
enable_infra2: false

# RGB camera only - minimal settings
rgb_camera.enable: true
rgb_camera.color_profile: "320x240x6"  # Minimal resolution/framerate
rgb_camera.enable_auto_exposure: true
rgb_camera.auto_exposure_limit: 50000  # Reduced for faster response
rgb_camera.brightness: 0
rgb_camera.contrast: 50
rgb_camera.gamma: 300
rgb_camera.saturation: 64

# Disable all IMU to reduce bandwidth
enable_gyro: false
enable_accel: false

# Power optimizations
clip_distance: 3.0