# Intel RealSense D435i Optimized Configuration
# This configuration is optimized for outdoor agricultural use
# with stable power supply and autonomous navigation

# Camera naming and namespacing
camera_name: "camera"
camera_namespace: "camera"

# Core features
enable_sync: true
enable_pointcloud: true
pointcloud.enable: true
align_depth.enable: true

# Depth camera settings - minimal bandwidth configuration
depth_module.enable: true
depth_module.profile: "424x240x15"  # Valid profile format: widthxheightxfps
depth_module.enable_auto_exposure: true
depth_module.auto_exposure_limit: 100000
depth_module.emitter_enabled: 0 # Disabled to reduce USB bandwidth (0=off, 1=on, 2=auto)
depth_module.laser_power: 150.0
depth_module.accuracy: 2

# RGB camera settings - DISABLED for NPU exploration
rgb_camera.enable: false
rgb_camera.profile: "424x240x15"  # Match depth resolution and framerate
rgb_camera.enable_auto_exposure: true
rgb_camera.auto_exposure_limit: 100000
rgb_camera.brightness: 0
rgb_camera.contrast: 50
rgb_camera.gamma: 300
rgb_camera.saturation: 64

# IMU settings - enabled for NPU exploration  
enable_gyro: true
enable_accel: true
gyro_fps: 63  # Reduced from 200 to lower bandwidth
accel_fps: 63  # Reduced from 250 to match gyro
unite_imu_method: "linear_interpolation"
hold_back_imu_for_frames: true

# Disable infrared cameras to reduce USB bandwidth and avoid issues
enable_infra1: false
enable_infra2: false

# Clip distance for outdoor use
clip_distance: 8.0

# IMU covariance settings
linear_accel_cov: 0.01
angular_velocity_cov: 0.01

# Quality settings - enable decimation to reduce point count
decimation_filter.enable: true
decimation_filter.magnitude: 2  # Reduce point cloud density for performance
temporal_filter.enable: true
spatial_filter.enable: true
hole_filling_filter.enable: true
disparity_filter.enable: false

# Performance settings
publish_tf: true
tf_publish_rate: 15.0