realsense_processor:
  ros__parameters:
    # Camera configuration
    camera_name: "realsense_435i"
    frame_id: "camera_link"
    depth_frame_id: "camera_depth_frame"
    
    # Stream configuration
    color_width: 640
    color_height: 480
    color_fps: 30
    depth_width: 640
    depth_height: 480
    depth_fps: 30
    
    # Processing parameters
    depth_scale: 0.001  # RealSense depth scale (mm to m)
    min_depth: 0.1      # meters
    max_depth: 10.0     # meters
    
    # Point cloud parameters
    enable_pointcloud: true
    pointcloud_decimation: 2  # Skip every N pixels
    
    # Image processing
    enable_align: true  # Align depth to color
    enable_colorizer: false
    
obstacle_detector:
  ros__parameters:
    # Detection parameters
    min_obstacle_height: 0.05  # meters
    max_obstacle_height: 2.0   # meters
    obstacle_threshold: 0.1    # meters from ground
    
    # Field of view for obstacle detection
    detection_width: 2.0       # meters left/right
    detection_distance: 3.0    # meters forward
    
    # Ground plane detection
    ground_plane_tolerance: 0.05  # meters
    min_points_for_plane: 1000
    
    # Clustering
    cluster_tolerance: 0.1     # meters
    min_cluster_size: 50
    max_cluster_size: 5000